const tracery = require("tracery-grammar");

const grammar = tracery.createGrammar({
  isms: [
    "abstract",
    "academic",
    "action painting",
    "art deco",
    "art nouveau",
    "avant-garde",
    "baroque",
    "bauhaus",
    "biedermeier",
    "caravaggisti",
    "carolingian",
    "classical",
    "cobra",
    "color field painting",
    "conceptual",
    "cubist",
    "cubo-futurist",
    "dada",
    "deformalist",
    "divisionist",
    "eclectic",
    "ego-futurist",
    "existentialist",
    "expressionist",
    "fauvist",
    "formalist",
    "futurist",
    "geometric",
    "gothic",
    "hard-edged",
    "historic",
    "humanist",
    "hyperrealist",
    "idealist",
    "illusionist",
    "impressionist",
    "incoherent",
    "international",
    "kinetic",
    "lettrist",
    "lowbrow",
    "luminist",
    "lyrical",
    "maximalist",
    "merovingian",
    "metaphysical",
    "minimalist",
    "modern",
    "modernist",
    "monumental",
    "multicultural",
    "naturalist",
    "neo-classical",
    "neo-expressionist",
    "neo-geo",
    "neo-impressionist",
    "neo-minimalist",
    "nonconforming",
    "performative",
    "photorealist",
    "pointilist",
    "post-conceptual",
    "post-impressionist",
    "post-minimal",
    "post-painterly abstraction",
    "post-structural",
    "postminimal",
    "postmodern",
    "realist",
    "relational",
    "rococo",
    "romantic",
    "secular",
    "situationist",
    "social realist",
    "structural",
    "superflat",
    "superstroke",
    "tonal",
  ],
  prepositions: [
    "aboard",
    "about",
    "above",
    "absent",
    "across",
    "after",
    "against",
    "along",
    "alongside",
    "amid",
    "amidst",
    "among",
    "amongst",
    "around",
    "as",
    "astride",
    "at",
    "atop",
    "before",
    "afore",
    "behind",
    "below",
    "beneath",
    "beside",
    "besides",
    "between",
    "beyond",
    "by",
    "circa",
    "despite",
    "down",
    "during",
    "except",
    "for",
    "from",
    "in",
    "inside",
    "into",
    "less",
    "like",
    "minus",
    "near",
    "nearer",
    "nearest",
    "notwithstanding",
    "of",
    "off",
    "on",
    "onto",
    "opposite",
    "outside",
    "over",
    "past",
    "per",
    "save",
    "since",
    "through",
    "throughout",
    "to",
    "toward",
    "towards",
    "under",
    "underneath",
    "until",
    "up",
    "upon",
    "upside",
    "versus",
    "via",
    "with",
    "within",
    "without",
    "worth",
    "according to",
    "adjacent to",
    "ahead of",
    "apart from",
    "as of",
    "as per",
    "aside from",
    "astern of",
    "back to",
    "because of",
    "close to",
    "due to",
    "except for",
    "far from",
    "inside of",
    "instead of",
    "left of",
    "near to",
    "next to",
    "opposite of",
    "opposite to",
    "out from",
    "out of",
    "outside of",
    "owing to",
    "prior to",
    "pursuant to",
    "rather than",
    "regardless of",
    "right of",
    "subsequent to",
    "such as",
    "thanks to",
    "up to",
    "as far as",
    "as opposed to",
    "as soon as",
    "as well as",
    "at the behest of",
    "by means of",
    "by virtue of",
    "for the sake of",
    "in accordance with",
    "in addition to",
    "in case of",
    "in front of",
    "in lieu of",
    "in place of",
    "in point of",
    "in spite of",
    "on account of",
    "on behalf of",
    "on top of",
    "with a view to",
  ],
  flowers: [
    "anemone",
    "amaryllis",
    "amaranth",
    "aster",
    "azalea",
    "baby's breath",
    "begonia",
    "bellflower",
    "bergamot",
    "bird of paradise",
    "bluebell",
    "bottlebrush",
    "buttercup",
    "camellias",
    "carnation",
    "columbine",
    "clover",
    "crocus",
    "daisy",
    "dahlia",
    "daffodil",
    "delphinium",
    "edelweiss",
    "primrose",
    "forget me not",
    "foxglove",
    "freesia",
    "gerbera daisy",
    "gladiolus",
    "hibiscus",
    "heather",
    "hyacinth",
    "holly",
    "iris",
    "jasmine",
    "ladys slipper",
    "lavender",
    "lilac",
    "lily",
    "lotus flower",
    "marigold",
    "marjoram",
    "mimosa",
    "narcissus",
    "orange blossom",
    "orchid",
    "peach blossom",
    "peony",
    "petunia",
    "rhododendron",
    "rosemary",
    "roses",
    "sage",
    "snapdragon",
    "sunflower",
    "tansy",
    "thistle",
    "thyme",
    "tulip",
    "violet",
    "water lily",
    "zinnia",
  ],
  descriptions: [
    "abnormal",
    "absent-minded",
    "adventurous",
    "affectionate",
    "agile",
    "agreeable",
    "alert",
    "amazing",
    "ambitious",
    "amiable",
    "amusing",
    "analytical",
    "angelic",
    "apathetic",
    "apprehensive",
    "ardent",
    "artificial",
    "artistic",
    "assertive",
    "attentive",
    "average",
    "awesome",
    "awful",
    "balanced",
    "beautiful",
    "beneficent",
    "blue",
    "blunt",
    "boisterous",
    "brave",
    "bright",
    "brilliant",
    "buff",
    "callous",
    "candid",
    "cantankerous",
    "capable",
    "careful",
    "careless",
    "caustic",
    "cautious",
    "charming",
    "childish",
    "childlike",
    "cheerful",
    "chic",
    "churlish",
    "circumspect",
    "clean",
    "clever",
    "clumsy",
    "coherent",
    "cold",
    "composed",
    "confident",
    "confused",
    "conscientious",
    "considerate",
    "content",
    "cool",
    "cool-headed",
    "cooperative",
    "cordial",
    "courageous",
    "cowardly",
    "crabby",
    "crafty",
    "cranky",
    "crass",
    "critical",
    "cruel",
    "curious",
    "cynical",
    "dainty",
    "decisive",
    "deep",
    "deferential",
    "deft",
    "delicate",
    "dependent",
    "delightful",
    "demure",
    "depressed",
    "devoted",
    "dextrous",
    "diligent",
    "direct",
    "dirty",
    "disagreeable",
    "discerning",
    "discreet",
    "disruptive",
    "distant",
    "distraught",
    "distrustful",
    "dowdy",
    "dramatic",
    "dreary",
    "drowsy",
    "drugged",
    "dull",
    "dutiful",
    "eager",
    "earnest",
    "efficient",
    "egotistical",
    "elfin",
    "emotional",
    "energetic",
    "enterprising",
    "enthusiastic",
    "evasive",
    "even-tempered",
    "exacting",
    "excellent",
    "excitable",
    "experienced",
    "fabulous",
    "fastidious",
    "ferocious",
    "fervent",
    "fiery",
    "flaky",
    "flashy",
    "frank",
    "friendly",
    "funny",
    "fussy",
    "generous",
    "gentle",
    "gloomy",
    "good",
    "grave",
    "great",
    "groggy",
    "grouchy",
    "guarded",
    "hearty",
    "helpful",
    "hesitant",
    "hypercritical",
    "hysterical",
    "idle",
    "illogical",
    "imaginative",
    "immature",
    "impatient",
    "imperturbable",
    "impetuous",
    "impractical",
    "impressionable",
    "impressive",
    "impulsive",
    "inactive",
    "incisive",
    "inconsistent",
    "independent",
    "indiscreet",
    "indolent",
    "indefatigable",
    "industrious",
    "inexperienced",
    "inspiring",
    "intelligent",
    "interesting",
    "inventive",
    "irascible",
    "irritable",
    "jocular",
    "jovial",
    "joyous",
    "kind",
    "lethargic",
    "level-headed",
    "listless",
    "lithe",
    "lively",
    "local",
    "logical",
    "long-winded",
    "lovable",
    "love-lorn",
    "lovely",
    "maternal",
    "mature",
    "meddlesome",
    "mercurial",
    "methodical",
    "meticulous",
    "mild",
    "modest",
    "motivated",
    "musical",
    "naive",
    "natural",
    "negative",
    "nervous",
    "noisy",
    "normal",
    "nosy",
    "numb",
    "obliging",
    "ostentatious",
    "outgoing",
    "outspoken",
    "passionate",
    "passive",
    "patient",
    "peaceful",
    "peevish",
    "pensive",
    "persnickety",
    "petulant",
    "picky",
    "plain",
    "playful",
    "pleasant",
    "plucky",
    "polite",
    "popular",
    "positive",
    "powerful",
    "practical",
    "pretty",
    "proficient",
    "proud",
    "provocative",
    "prudent",
    "punctual",
    "querulous",
    "quick",
    "quiet",
    "realistic",
    "reassuring",
    "reclusive",
    "reliable",
    "reluctant",
    "resentful",
    "reserved",
    "resourceful",
    "responsible",
    "restless",
    "revered",
    "ridiculous",
    "sassy",
    "saucy",
    "sedate",
    "self-assured",
    "sensible",
    "sensitive",
    "sentimental",
    "serene",
    "shy",
    "silly",
    "sincere",
    "sleepy",
    "slight",
    "slow",
    "smart",
    "snazzy",
    "sober",
    "sophisticated",
    "soulful",
    "sour",
    "spirited",
    "stable",
    "staid",
    "steady",
    "stern",
    "stoic",
    "striking",
    "strong",
    "sturdy",
    "subtle",
    "sullen",
    "sulky",
    "supercilious",
    "superficial",
    "sweet",
    "tactful",
    "talented",
    "thinking",
    "thoughtful",
    "timid",
    "tired",
    "tolerant",
    "touchy",
    "tranquil",
    "unaffected",
    "unbalanced",
    "uncertain",
    "uncooperative",
    "unguarded",
    "unsure",
    "unwilling",
    "venal",
    "versatile",
    "vigilant",
    "warm",
    "warmhearted",
    "wary",
    "watchful",
    "weak",
    "well-behaved",
    "well-developed",
    "well-intentioned",
    "well-respected",
    "well-rounded",
    "willing",
    "wonderful",
    "volcanic",
    "vulnerable",
    "zealous",
  ],
  universals: [
    "abstraction in speech and thought",
    "actions under self-control distinguished from those not under control",
    "aesthetics",
    "affection expressed and felt",
    "ambivalence",
    "anthropomorphisation",
    "anticipation",
    "antonyms",
    "attachment",
    "baby talk",
    "belief in the supernatural",
    "false beliefs",
    "beliefs about disease",
    "beliefs about fortune and misfortune",
    "binary cognitive distinctions",
    "body adornment",
    "childbirth customs",
    "childcare",
    "childhood fantasies",
    "choice making",
    "classification",
    "classification of age",
    "classification of behavioral propensities",
    "classification of colours",
    "classification of fauna",
    "classification of flora",
    "classification of inner states",
    "classification of kin",
    "classification of space",
    "classification of tools",
    "classification of weather",
    "coalitions",
    "collective identities",
    "conflict",
    "mediation of conflict",
    "conjectural reasoning",
    "containers",
    "meaningful elements in language",
    "cooking",
    "cooperation",
    "perpetual statuses",
    "coyness display",
    "critical learning",
    "crying",
    "daily routines",
    "dance",
    "death rituals",
    "decision making",
    "discrepancies between speech, thought and action",
    "distinguishing right and wrong",
    "diurnality",
    "divination",
    "division of labour",
    "dominance/submission",
    "dreams",
    "dream interpretation",
    "economic inequalities",
    "emotions",
    "empathy",
    "entification",
    "envy",
    "etiquette",
    "explanation",
    "facial communication",
    "fairness and equity",
    "family (or household)",
    "fears",
    "feasting",
    "figurative speech",
    "fire",
    "gestures",
    "gift giving",
    "gossip",
    "grammar",
    "group living",
    "habituation",
    "hairstyles",
    "healing the sick",
    "hope",
    "hospitality",
    "imagery",
    "intention",
    "interpolation",
    "interpreting behavior",
    "intertwining",
    "jokes",
    "judging others",
    "kinship statuses",
    "language",
    "language employed to manipulate others",
    "language employed to misinform or mislead",
    "language as not a simple reflection of reality",
    "law",
    "leaders",
    "likes and dislikes",
    "logical notions",
    "magic",
    "magic to increase life",
    "magic to sustain life",
    "magic to win love",
    "making comparisons",
    "marriage",
    "materialism",
    "meal times",
    "measuring",
    "medicine",
    "melody",
    "memory",
    "mental maps",
    "metonym",
    "mood- or consciousness-altering techniques",
    "moral sentiments",
    "morphemes",
    "mourning",
    "music",
    "musical repitition",
    "musical variation",
    "myths",
    "narrative",
    "nouns",
    "onomatopoeia",
    "overestimating objectivity of thought",
    "pain",
    "past/present/future",
    "personal names",
    "planning",
    "planning for future",
    "play",
    "poetry/rhetoric",
    "poetic lines characterized by repetition and variation",
    "poetic lines demarcated by pauses",
    "polysemy",
    "prestige inequalities",
    "pretend play",
    "pride",
    "private inner life",
    "promise",
    "pronouns",
    "proper names",
    "property",
    "proverbs",
    "psychological defense mechanisms",
    "reciprocal exchange)",
    "redress of wrongs",
    "rhythm",
    "risk-taking",
    "rites of passage",
    "rituals",
    "self-control",
    "self distinguished from other",
    "self as neither wholly passive nor wholly autonomous",
    "self as subject and object",
    "semantics",
    "semantic components",
    "senses unified",
    "sexual attraction",
    "sexual modesty",
    "sexual regulation",
    "shame",
    "shelter",
    "sickness and death seen as related",
    "social structure",
    "symbolism",
    "symbolic speech",
    "synesthetic metaphors",
    "synonyms",
    "taboos",
    "territoriality",
    "time",
    "time, cyclicity of",
    "toys, playthings",
    "triangular awareness",
    "turn-taking",
    "units of time",
    "verbs",
    "vowel contrasts",
  ],
  wayOfFeeling: [
    "feeling",
    "emotionally",
    "silently",
    "secretly",
    "abashedly",
    "undoubtably",
    "better than",
    "agonisingly",
    "thoroughly",
    "falteringly",
    "disturbingly",
    "less than",
    "quite",
    "not quite",
    "swiftly",
    "painstakingly",
    "notwithstanding",
    "perhaps",
    "despite being",
    "in wonderment,",
    "perchance",
    "beyond",
    "a bit",
    "surprisingly",
    "fantastically",
    "just a little",
  ],
  season: ["Winter", "Spring", "Summer", "Fall"],
  sensation: [
    "scent of",
    "feeling of",
    "essence of",
    "aroma of",
    "hint of",
    "trace of",
    "residue of",
    "hardly any",
    "a bounty of",
    "#season#",
  ],
  happens: [
    "stays with me",
    "lingers",
    "like a promise",
    "evokes permanence",
    "provokes wonder",
    "parses memory",
    "washes me clean",
    "transports me",
    "takes me away",
    "is transcendent",
    "reminds me of #season#",
    "brings evergreen longing",
    "a quintessential sensation",
    "forever",
    "atop the mountain",
    "by the lake",
    "near granite boulders",
    "illuminates what was lost",
    "and I am perpetual",
  ],
  plants: [
    "cinnamon",
    "African rice",
    "African violet",
    "alder",
    "almond",
    "American cress",
    "American dogwood",
    "American nightshade",
    "American white hellebore",
    "American winterberry",
    "Amy root",
    "annual sow thistle",
    "Appalachian tea",
    "apple of Sodom",
    "apple",
    "apricot",
    "Arizona sycamore",
    "arrowwood",
    "ash-leaved maple",
    "ash",
    "azolla",
    "baby rose",
    "bamboo",
    "banana",
    "bank cress",
    "baobab",
    "bastard pellitory",
    "bay laurel",
    "bay",
    "bean",
    "bear corn",
    "bearberry",
    "beech",
    "Belle Isle cress",
    "Bermuda cress",
    "big hellebore",
    "birch",
    "bird's nest plant",
    "bird's nest",
    "bitter nightshade",
    "bittercress",
    "bittersweet",
    "bitterweed",
    "black alder",
    "black ash",
    "black birch",
    "black cap",
    "black cherry",
    "black hellebore",
    "black maple",
    "black nightshade",
    "black raspberry",
    "black-eyed Susan",
    "black-weed",
    "blackberry",
    "blue ash",
    "blue bindweed",
    "blue oak",
    "blue-of-the-heavens",
    "blueberry cornel",
    "blueberry",
    "blunt-leaved milkweed",
    "bolean birch",
    "Boston fern or sword fern",
    "bow-wood",
    "box",
    "boxelder",
    "boxwood",
    "brilliant coneflower",
    "bristly dewberry",
    "bristly groundberry",
    "brittlebush",
    "broadleaf plantain",
    "broadleaf",
    "brown betty",
    "brown daisy",
    "brown-eyed Susan",
    "buffalo weed",
    "bulbous cress",
    "bull nettle",
    "bur oak",
    "butterfly flower",
    "butterfly weed",
    "cabbage",
    "cabinet cherry",
    "California bay",
    "California sycamore",
    "California thistle",
    "California walnut",
    "Canada root",
    "Canada thistle",
    "cancer jalap",
    "cane ash",
    "canoe birch",
    "Carolina azolla",
    "Carolina horse nettle",
    "carrot weed",
    "carrot",
    "cart track plant",
    "Catalina ironwood",
    "champion oak",
    "cherry birch",
    "cherry",
    "chestnut",
    "chigger flower",
    "Christmas fern",
    "chrysanthemum",
    "climbing nightshade",
    "clove",
    "clover",
    "clumpfoot cabbage",
    "coakum",
    "coast live oak",
    "coast polypody",
    "coconut",
    "coffee plant",
    "colic weed",
    "collard",
    "common alder",
    "common daisy, daisy",
    "common fig",
    "common milkweed",
    "common onion",
    "common plantain",
    "common ragweed",
    "common ragwort",
    "common serviceberry",
    "common tansy",
    "common yarrow",
    "cork oak",
    "corn sow thistle",
    "corn speedwell",
    "corn thistle",
    "cornelian tree",
    "corydalis",
    "cotton plant",
    "coyote willow",
    "creek maple",
    "creeping thistle",
    "creeping yellowcress",
    "cress",
    "crow's nest",
    "crow's toes",
    "crowfoot",
    "cucumber",
    "cursed thistle",
    "cutleaf coneflower",
    "cutleaf maple",
    "cutleaf toothwort",
    "damask violet",
    "dame's gilliflower",
    "dame's rocket",
    "dame's violet",
    "deadly nightshade",
    "deadnettle",
    "deciduous holly",
    "devil's bite",
    "devil's darning needle",
    "devil's nose",
    "devil's plague",
    "dindle",
    "dog's-tooth violet",
    "dogwood",
    "dooryard plantain",
    "downy serviceberry",
    "drumstick",
    "duck retten",
    "duscle",
    "dwarf wild rose",
    "dye-leaves",
    "dyer's oak",
    "early wintercress",
    "earth gall",
    "eastern black oak",
    "eastern coneflower",
    "eastern redbud",
    "English bull's eye",
    "English oak",
    "eucalyptus",
    "European flax",
    "European holly",
    "European pellitory",
    "European weeping birch",
    "European white birch",
    "European white hellebore",
    "evergreen huckleberry",
    "evergreen winterberry",
    "extinguisher moss",
    "eytelia",
    "fair-maid-of-France",
    "false alder",
    "false box",
    "false boxwood",
    "false hellebore",
    "fellenwort",
    "felonwood",
    "felonwort",
    "fennel",
    "fern-leaf corydalis",
    "fernleaf yarrow",
    "feverbush",
    "feverfew",
    "field sow thistle",
    "fig",
    "Florida dogwood",
    "flowering dogwood",
    "flowering dogwood",
    "fluxroot",
    "gallberry",
    "garden nightshade",
    "garget",
    "garlic mustard",
    "garlic root",
    "giant onion",
    "giant ragweed",
    "gloriosa daisy",
    "golden buttons",
    "golden corydalis",
    "golden garlic",
    "golden jerusalem",
    "goldenglow",
    "goodding willow",
    "goose tongue",
    "gordaldo",
    "grapefruit",
    "grapevine",
    "gray alder",
    "gray birch",
    "great ragweed",
    "greater plantain",
    "green ash",
    "green thistle",
    "green-headed coneflower",
    "groundberry",
    "gutweed",
    "hairy bittercress",
    "haldi",
    "hard thistle",
    "hare's colwort",
    "hare's thistle",
    "hay fever weed",
    "healing blade",
    "hedge plant",
    "hellebore",
    "hemp dogbane",
    "hemp",
    "hen plant",
    "henbit deadnettle",
    "herb barbara",
    "hispid swamp blackberry",
    "hoary ragwort",
    "hogweed",
    "holly",
    "honey mesquite",
    "horse cane",
    "horse nettle",
    "horsetail milkweed",
    "hound's berry",
    "houseleek",
    "huckleberry",
    "inkberry holly",
    "inkberry",
    "island oak",
    "isle of man cabbage",
    "itchweed",
    "ivy",
    "jack-by-the-hedge",
    "jack-in-the-bush",
    "Japanese flowering dogwood",
    "judas-tree",
    "juneberry",
    "juniper",
    "keek",
    "Kimberly queen fern",
    "kinnikinnik",
    "Korean rock fern",
    "kousa dogwood",
    "kousa",
    "kudzu",
    "laceflower",
    "lamb's cress",
    "lamb's foot",
    "land cress",
    "lavender",
    "leatherleaf viburnum",
    "leek",
    "lemon",
    "lettuce",
    "lily leek",
    "love vine",
    "low rose",
    "mahogany birch",
    "maize",
    "mango",
    "maple ash",
    "maple ash",
    "maple",
    "marsh ragwort",
    "meadow cabbage",
    "meadow holly",
    "mesquite",
    "milfoil",
    "milk thistle",
    "milkweed",
    "milky tassel",
    "mirbeck's oak",
    "moose maple",
    "moosewood",
    "mosquito fern",
    "mosquito plant",
    "mossycup white oak",
    "mother-of-the-evening",
    "mountain mahogany",
    "mulberry",
    "multiflora rose",
    "neem",
    "New Zealand flax",
    "night scented gilliflower",
    "nodding onion",
    "nodding thistle",
    "northern red oak",
    "nosebleed",
    "olive",
    "onion",
    "orange coneflower",
    "orange milkweed",
    "orange swallow-wort",
    "orange swallow-wort",
    "orange-root",
    "osage orange",
    "osage",
    "oxford ragwort",
    "pacific dogwood",
    "pale corydalis",
    "paper birch",
    "parsley",
    "parsnip",
    "peas",
    "peach",
    "peanut",
    "pear",
    "pedunculate oak",
    "Pennsylvania blackberry",
    "penny hedge",
    "pepper root",
    "perennial thistle",
    "petty morel",
    "pigeon berry",
    "pin oak",
    "pine",
    "pineapple",
    "pink corydalis",
    "pistachio",
    "plane (european sycamore)",
    "pleurisy root",
    "pocan bush",
    "poison ivy",
    "poisonberry",
    "poisonflower",
    "poke",
    "pokeroot",
    "pokeweed",
    "polecat weed",
    "polkweed",
    "poor Annie",
    "poor man's mustard",
    "poorland daisy",
    "poplar",
    "poppy",
    "possumhaw",
    "potato",
    "prairie rose",
    "prickly thistle",
    "pudina",
    "purple raspberry",
    "purple-flowered toothwort",
    "queen anne's lace",
    "queen's gilliflower",
    "quercitron",
    "radical weed",
    "ragweed",
    "ragwort",
    "rambler rose",
    "rantipole",
    "rapeseed",
    "raspberry",
    "red ash",
    "red birch",
    "red ink plant",
    "red mulberry",
    "red oak",
    "red osier",
    "red river maple",
    "red willow",
    "redbrush",
    "redbud",
    "redweed",
    "redwood sorrel",
    "rheumatism root",
    "rhubarb",
    "ribwort",
    "river ash",
    "river birch",
    "river maple",
    "roadweed",
    "rock harlequin",
    "rocket",
    "rocketcress",
    "rogue's gilliflower",
    "roman wormwood",
    "rose milkweed",
    "rose willow",
    "rose",
    "rosemary",
    "roundleaf plantain",
    "rum cherry",
    "running swamp blackberry",
    "rye",
    "saffron crocus",
    "sand brier",
    "sanguinary",
    "sauce-alone",
    "scarlet berry",
    "scarlet oak",
    "scoke",
    "scotch cap",
    "scrambled eggs",
    "screwbean mesquite",
    "scrub oak",
    "scurvy cress",
    "scurvy grass",
    "serviceberry",
    "sessile oak",
    "shadblow serviceberry",
    "shadblow",
    "shadbush",
    "sharp-fringed sow thistle",
    "silkweed",
    "silky cornel",
    "silky dogwood",
    "silky swallow-wort",
    "silky swallow-wort",
    "silver birch",
    "silver maple",
    "silver ragwort",
    "silverleaf maple",
    "skunk cabbage",
    "skunkweed",
    "small-flowered thistle",
    "snakeberry",
    "sneezeweed",
    "sneezewort yarrow",
    "sneezewort",
    "snowdrop",
    "soft maple",
    "soldier's woundwort",
    "sorrel",
    "spanish oak",
    "speckled alder",
    "spice birch",
    "spiny sow thistle",
    "spiny-leaved sow thistle",
    "spoolwood",
    "spotted deadnettle",
    "spotted oak",
    "spring cress",
    "squaw bush",
    "stag bush",
    "stammerwort",
    "star-of-persia",
    "stickweed",
    "strawberry tree 'marina'",
    "strawberry tree",
    "strawberry",
    "striped alder",
    "striped maple",
    "sugar maple",
    "sugarcane",
    "sugarplum",
    "summer lilac",
    "sunflower",
    "swamp ash",
    "swamp cabbage",
    "swamp dewberry",
    "swamp dogwood",
    "swamp hellebore",
    "swamp holly",
    "swamp maple",
    "swamp milkweed",
    "swamp oak",
    "swamp silkweed",
    "swamp Spanish oak",
    "swamp white oak",
    "sweet birch",
    "sweet orange",
    "sweet potato vine",
    "sweet potato",
    "sweet rocket",
    "swine thistle",
    "swinies",
    "sword ferns",
    "sycamore",
    "tall ambrosia",
    "tall coneflower",
    "tassel weed",
    "tea",
    "thimbleberry",
    "thimbleweed",
    "thin-leaved coneflower",
    "thistle",
    "thousand-leaf",
    "thousand-seal",
    "three-leaved coneflower",
    "thyme",
    "tickleweed",
    "tobacco plant",
    "tomato",
    "toothwort",
    "touch-me-not",
    "trailing bittersweet",
    "trailing nightshade",
    "trailing red huckleberry",
    "trailing violet nightshade",
    "traveller's joy",
    "tread-softly",
    "tree onion",
    "tree sow thistle",
    "tree tobacco",
    "trillium",
    "tuber-root",
    "tulip",
    "tulsi",
    "upland cress",
    "valley oak",
    "vanilla orchid",
    "viburnum",
    "violet bloom",
    "violet",
    "virgin's bower",
    "Virginia silkweed",
    "Virginia virgin's bower",
    "Virginia winterberry",
    "wall speedwell",
    "walnut",
    "water ash",
    "water birch",
    "water fern",
    "water maple",
    "way thistle",
    "waybread",
    "wayside plantain",
    "weeping birch",
    "western redbud",
    "western redbud",
    "western sword fern",
    "western trillium",
    "western wake robin",
    "wheat",
    "whiskey cherry",
    "white alder",
    "white ash",
    "white birch",
    "white cornel",
    "white hellebore",
    "white man's foot",
    "white maple",
    "white mulberry",
    "white oak",
    "white tansy",
    "white trillium",
    "white-root",
    "whorled milkweed",
    "wild black cherry",
    "wild carrot",
    "wild cherry",
    "wild cotton",
    "wild garlic",
    "wild hops",
    "wild onion",
    "wild orange",
    "wild pellitory",
    "wild rose",
    "wild tansy",
    "willow",
    "windroot",
    "wineberry",
    "winter gilliflower",
    "winter rocket",
    "winterberry holly",
    "winterberry",
    "wintercress",
    "woodbine",
    "woody nightshade",
    "woolly yarrow",
    "wound rocket",
    "yarrow",
    "yellow birch",
    "yellow coneflower",
    "yellow corydalis",
    "yellow daisy",
    "yellow fieldcress",
    "yellow fumewort",
    "yellow harlequin",
    "yellow milkweed",
    "yellow ox-eye daisy",
    "yellow rocket",
    "yellowbark oak",
    "yellowwood",
    "zedoary",
  ],
  longSentence: [
    "#plants.capitalize# #prepositions# #flowers# #prepositions# #universals#.",
    "#sensation.a.capitalize# #plants# #happens#.",
  ],
  shortSentence: [
    "#wayOfFeeling.capitalize# #descriptions#.",
    "#wayOfFeeling.capitalize# #isms#.",
  ],
  combo: ["#longSentence# #shortSentence#", "#shortSentence# #longSentence#"],
  origin: ["#combo#"],
});

grammar.addModifiers(tracery.baseEngModifiers);

const getTweet = function () {
  return grammar.flatten("#origin#");
};

module.exports = getTweet;
